name: build and publish windows

env:
  TARGET_NAME: Lab2QRCode-HttpService

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [
          windows-latest,
          ubuntu-latest
        ]
        toolchain: [ msvc, clang, gcc ]
        mode: [ Debug, Release ]
        include:
          - os: windows-latest
            toolchain: msvc
          - os: windows-latest
            toolchain: clang
          - os: ubuntu-latest
            toolchain: gcc
          - os: ubuntu-latest
            toolchain: clang
        exclude:
          - os: windows-latest
            toolchain: gcc
          - os: ubuntu-latest
            toolchain: msvc


    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Zlib
        shell: bash
        run: |
          git clone --depth 1 https://github.com/madler/zlib.git ../zlib --recurse
          cmake -S ../zlib -B ../zlib/build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
          cmake --build ../zlib/build --config ${{ matrix.mode }}
          cmake --install ../zlib/build --prefix "${{ github.workspace }}/deps"

      - name: Setup libhv
        shell: bash
        run: |
          git clone --depth 1 https://github.com/ithewei/libhv.git ../libhv --recurse
          cmake -S ../libhv -B ../libhv/build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
          cmake --build ../libhv/build --config ${{ matrix.mode }}
          cmake --install ../libhv/build --prefix "${{ github.workspace }}/deps"

      - name: Build ${{ matrix.mode }}
        shell: bash
        run: |
          cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_PREFIX_PATH="./deps"
          cmake --build ./build --config ${{ matrix.mode }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{env.TARGET_NAME}}-${{matrix.os}}
          path: "${{ env.release_dir }}"
