name: build and publish windows

env:
  TARGET_NAME: Lab2QRCode-HttpService

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        toolchain: [ cl, clang, gcc ]
        mode: [ Debug, Release ]
        include:
          - os: windows-latest
            toolchain: cl
          - os: windows-latest
            toolchain: clang
          - os: ubuntu-latest
            toolchain: gcc
          - os: ubuntu-latest
            toolchain: clang
        exclude:
          - os: windows-latest
            toolchain: gcc
          - os: ubuntu-latest
            toolchain: cl

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC Developer Command Prompt
        if: "${{ matrix.os }}" == "windows-latest"
        uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: x64

      - name: Setup Zlib
        shell: bash
        run: |
          git clone --depth 1 https://github.com/madler/zlib.git ../zlib --recurse
          cmake -S ../zlib -B ../zlib/build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
          cmake --build ../zlib/build --config ${{ matrix.mode }}
          cmake --install ../zlib/build --prefix "${{ github.workspace }}/deps"

      - name: Setup spdlog
        shell: bash
        run: |
          git clone --depth 1 https://github.com/gabime/spdlog.git ../spdlog --recurse
          cmake -S ../spdlog -B ../spdlog/build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DSPDLOG_BUILD_EXAMPLE=OFF -DSPDLOG_BUILD_TESTS=OFF -DSPDLOG_BUILD_SHARED=OFF
          cmake --build ../spdlog/build --config ${{ matrix.mode }}
          cmake --install ../spdlog/build --prefix "${{ github.workspace }}/deps"

      - name: Build ${{ matrix.mode }}
        shell: bash
        run: |
          cmake -S . -B ./build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.mode }} -DCMAKE_PREFIX_PATH="./deps"
          cmake --build ./build --config ${{ matrix.mode }}
